server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul: 
  #ignored-services: microservicecloud-dept
  prefix: /demo
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicecloud-role
    mydept.path: /myrole/**
 
info:
  app.name: mydemo-microcloud
  company.name: www.mydemo.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

